export type UniverseCategory = 'AI Stack' | 'CEDEAR' | 'BYMA'

export interface UniverseEntry {
  ticker: string
  name: string
  layer: string
  category: UniverseCategory
}

const RAW_UNIVERSE: UniverseEntry[] = [
  // ── AI Stack ────────────────────────────────────────────────────────────────
  { ticker: 'NVDA',  name: 'Nvidia',                   layer: 'Chip Design',       category: 'AI Stack' },
  { ticker: 'AMD',   name: 'AMD',                      layer: 'Chip Design',       category: 'AI Stack' },
  { ticker: 'AVGO',  name: 'Broadcom',                 layer: 'Chip Design',       category: 'AI Stack' },
  { ticker: 'INTC',  name: 'Intel',                    layer: 'Chip Design',       category: 'AI Stack' },
  { ticker: 'QCOM',  name: 'Qualcomm',                 layer: 'Chip Design',       category: 'AI Stack' },
  { ticker: 'MSFT',  name: 'Microsoft',                layer: 'Hyperscaler',       category: 'AI Stack' },
  { ticker: 'GOOGL', name: 'Alphabet',                 layer: 'Hyperscaler',       category: 'AI Stack' },
  { ticker: 'AMZN',  name: 'Amazon',                   layer: 'Hyperscaler',       category: 'AI Stack' },
  { ticker: 'META',  name: 'Meta',                     layer: 'Hyperscaler',       category: 'AI Stack' },
  { ticker: 'ASML',  name: 'ASML',                     layer: 'Semi Equipment',    category: 'AI Stack' },
  { ticker: 'LRCX',  name: 'Lam Research',             layer: 'Semi Equipment',    category: 'AI Stack' },
  { ticker: 'KLAC',  name: 'KLA Corp',                 layer: 'Semi Equipment',    category: 'AI Stack' },
  { ticker: 'AMAT',  name: 'Applied Materials',        layer: 'Semi Equipment',    category: 'AI Stack' },
  { ticker: 'NET',   name: 'Cloudflare',               layer: 'Edge / Cloud',      category: 'AI Stack' },
  { ticker: 'ORCL',  name: 'Oracle',                   layer: 'Edge / Cloud',      category: 'AI Stack' },
  { ticker: 'EQIX',  name: 'Equinix',                  layer: 'DC REIT',           category: 'AI Stack' },
  { ticker: 'TSM',   name: 'TSMC (ADR)',               layer: 'Semi Mfg',          category: 'AI Stack' },

  // ── CEDEARs — Technology ─────────────────────────────────────────────────────
  { ticker: 'AAPL',  name: 'Apple',                    layer: 'Technology',        category: 'CEDEAR' },
  { ticker: 'TSLA',  name: 'Tesla',                    layer: 'Technology',        category: 'CEDEAR' },
  { ticker: 'NFLX',  name: 'Netflix',                  layer: 'Technology',        category: 'CEDEAR' },
  { ticker: 'ADBE',  name: 'Adobe',                    layer: 'Technology',        category: 'CEDEAR' },
  { ticker: 'CRM',   name: 'Salesforce',               layer: 'Technology',        category: 'CEDEAR' },
  { ticker: 'IBM',   name: 'IBM',                      layer: 'Technology',        category: 'CEDEAR' },
  { ticker: 'CSCO',  name: 'Cisco',                    layer: 'Technology',        category: 'CEDEAR' },
  { ticker: 'TXN',   name: 'Texas Instruments',        layer: 'Technology',        category: 'CEDEAR' },
  { ticker: 'MU',    name: 'Micron',                   layer: 'Technology',        category: 'CEDEAR' },
  { ticker: 'MRVL',  name: 'Marvell Technology',       layer: 'Technology',        category: 'CEDEAR' },
  { ticker: 'ADI',   name: 'Analog Devices',           layer: 'Technology',        category: 'CEDEAR' },
  { ticker: 'ARM',   name: 'ARM Holdings',             layer: 'Technology',        category: 'CEDEAR' },
  { ticker: 'SHOP',  name: 'Shopify',                  layer: 'Technology',        category: 'CEDEAR' },
  { ticker: 'PYPL',  name: 'PayPal',                   layer: 'Technology',        category: 'CEDEAR' },
  { ticker: 'UBER',  name: 'Uber',                     layer: 'Technology',        category: 'CEDEAR' },
  { ticker: 'SPOT',  name: 'Spotify',                  layer: 'Technology',        category: 'CEDEAR' },
  { ticker: 'SNAP',  name: 'Snap',                     layer: 'Technology',        category: 'CEDEAR' },
  { ticker: 'BABA',  name: 'Alibaba',                  layer: 'Technology',        category: 'CEDEAR' },
  { ticker: 'MELI',  name: 'MercadoLibre',             layer: 'Technology',        category: 'CEDEAR' },
  { ticker: 'GLOB',  name: 'Globant',                  layer: 'Technology',        category: 'CEDEAR' },
  { ticker: 'DESP',  name: 'Despegar',                 layer: 'Technology',        category: 'CEDEAR' },
  { ticker: 'COIN',  name: 'Coinbase',                 layer: 'Technology',        category: 'CEDEAR' },
  { ticker: 'PLTR',  name: 'Palantir',                 layer: 'Technology',        category: 'CEDEAR' },
  { ticker: 'SNOW',  name: 'Snowflake',                layer: 'Technology',        category: 'CEDEAR' },
  { ticker: 'ROKU',  name: 'Roku',                     layer: 'Technology',        category: 'CEDEAR' },
  { ticker: 'DOCU',  name: 'DocuSign',                 layer: 'Technology',        category: 'CEDEAR' },
  { ticker: 'TWLO',  name: 'Twilio',                   layer: 'Technology',        category: 'CEDEAR' },
  { ticker: 'PINS',  name: 'Pinterest',                layer: 'Technology',        category: 'CEDEAR' },
  { ticker: 'ETSY',  name: 'Etsy',                     layer: 'Technology',        category: 'CEDEAR' },
  { ticker: 'EBAY',  name: 'eBay',                     layer: 'Technology',        category: 'CEDEAR' },
  { ticker: 'EA',    name: 'Electronic Arts',          layer: 'Technology',        category: 'CEDEAR' },
  { ticker: 'ISRG',  name: 'Intuitive Surgical',       layer: 'Technology',        category: 'CEDEAR' },
  { ticker: 'BKNG',  name: 'Booking Holdings',         layer: 'Technology',        category: 'CEDEAR' },
  { ticker: 'GRMN',  name: 'Garmin',                   layer: 'Technology',        category: 'CEDEAR' },
  { ticker: 'MSI',   name: 'Motorola Solutions',       layer: 'Technology',        category: 'CEDEAR' },
  { ticker: 'SWKS',  name: 'Skyworks Solutions',       layer: 'Technology',        category: 'CEDEAR' },
  { ticker: 'INFY',  name: 'Infosys (ADR)',            layer: 'Technology',        category: 'CEDEAR' },
  { ticker: 'SAP',   name: 'SAP SE (ADR)',             layer: 'Technology',        category: 'CEDEAR' },
  { ticker: 'ACN',   name: 'Accenture',                layer: 'Technology',        category: 'CEDEAR' },
  { ticker: 'ADP',   name: 'ADP',                      layer: 'Technology',        category: 'CEDEAR' },
  { ticker: 'VRSN',  name: 'VeriSign',                 layer: 'Technology',        category: 'CEDEAR' },
  { ticker: 'EFX',   name: 'Equifax',                  layer: 'Technology',        category: 'CEDEAR' },
  { ticker: 'SPGI',  name: 'S&P Global',               layer: 'Technology',        category: 'CEDEAR' },
  { ticker: 'TCOM',  name: 'Trip.com (ADR)',           layer: 'Technology',        category: 'CEDEAR' },
  { ticker: 'JD',    name: 'JD.com (ADR)',             layer: 'Technology',        category: 'CEDEAR' },
  { ticker: 'NTES',  name: 'NetEase (ADR)',            layer: 'Technology',        category: 'CEDEAR' },
  { ticker: 'BIDU',  name: 'Baidu (ADR)',              layer: 'Technology',        category: 'CEDEAR' },
  { ticker: 'NIO',   name: 'NIO Inc',                  layer: 'Technology',        category: 'CEDEAR' },
  { ticker: 'SE',    name: 'Sea Ltd',                  layer: 'Technology',        category: 'CEDEAR' },
  { ticker: 'NU',    name: 'Nu Holdings',              layer: 'Technology',        category: 'CEDEAR' },
  { ticker: 'PAGS',  name: 'PagSeguro (ADR)',          layer: 'Technology',        category: 'CEDEAR' },
  { ticker: 'STNE',  name: 'StoneCo',                  layer: 'Technology',        category: 'CEDEAR' },
  { ticker: 'XP',    name: 'XP Inc',                   layer: 'Technology',        category: 'CEDEAR' },
  { ticker: 'SQ',    name: 'Block Inc',                layer: 'Technology',        category: 'CEDEAR' },
  { ticker: 'SONY',  name: 'Sony (ADR)',               layer: 'Technology',        category: 'CEDEAR' },
  { ticker: 'ERIC',  name: 'Ericsson (ADR)',           layer: 'Technology',        category: 'CEDEAR' },
  { ticker: 'NOK',   name: 'Nokia (ADR)',              layer: 'Technology',        category: 'CEDEAR' },
  { ticker: 'GLW',   name: 'Corning',                  layer: 'Technology',        category: 'CEDEAR' },
  { ticker: 'HPQ',   name: 'HP Inc',                   layer: 'Technology',        category: 'CEDEAR' },
  { ticker: 'SIEGY', name: 'Siemens (ADR)',            layer: 'Technology',        category: 'CEDEAR' },
  { ticker: 'PHG',   name: 'Philips (ADR)',            layer: 'Technology',        category: 'CEDEAR' },
  { ticker: 'ADDYY', name: 'Adidas (ADR)',             layer: 'Technology',        category: 'CEDEAR' },

  // ── CEDEARs — Financials ──────────────────────────────────────────────────────
  { ticker: 'JPM',   name: 'JPMorgan Chase',           layer: 'Financials',        category: 'CEDEAR' },
  { ticker: 'BAC',   name: 'Bank of America',          layer: 'Financials',        category: 'CEDEAR' },
  { ticker: 'GS',    name: 'Goldman Sachs',            layer: 'Financials',        category: 'CEDEAR' },
  { ticker: 'MS',    name: 'Morgan Stanley',           layer: 'Financials',        category: 'CEDEAR' },
  { ticker: 'V',     name: 'Visa',                     layer: 'Financials',        category: 'CEDEAR' },
  { ticker: 'MA',    name: 'Mastercard',               layer: 'Financials',        category: 'CEDEAR' },
  { ticker: 'BRK-B', name: 'Berkshire Hathaway B',    layer: 'Financials',        category: 'CEDEAR' },
  { ticker: 'C',     name: 'Citigroup',                layer: 'Financials',        category: 'CEDEAR' },
  { ticker: 'AXP',   name: 'American Express',         layer: 'Financials',        category: 'CEDEAR' },
  { ticker: 'SCHW',  name: 'Charles Schwab',           layer: 'Financials',        category: 'CEDEAR' },
  { ticker: 'USB',   name: 'US Bancorp',               layer: 'Financials',        category: 'CEDEAR' },
  { ticker: 'WFC',   name: 'Wells Fargo',              layer: 'Financials',        category: 'CEDEAR' },
  { ticker: 'BK',    name: 'Bank of NY Mellon',        layer: 'Financials',        category: 'CEDEAR' },
  { ticker: 'TRV',   name: 'Travelers',                layer: 'Financials',        category: 'CEDEAR' },
  { ticker: 'AIG',   name: 'AIG',                      layer: 'Financials',        category: 'CEDEAR' },
  { ticker: 'MMC',   name: 'Marsh & McLennan',         layer: 'Financials',        category: 'CEDEAR' },
  { ticker: 'HSBC',  name: 'HSBC (ADR)',               layer: 'Financials',        category: 'CEDEAR' },
  { ticker: 'BCS',   name: 'Barclays (ADR)',           layer: 'Financials',        category: 'CEDEAR' },
  { ticker: 'ING',   name: 'ING Groep (ADR)',          layer: 'Financials',        category: 'CEDEAR' },
  { ticker: 'BBVA',  name: 'BBVA (ADR)',               layer: 'Financials',        category: 'CEDEAR' },
  { ticker: 'SAN',   name: 'Santander (ADR)',          layer: 'Financials',        category: 'CEDEAR' },
  { ticker: 'LYG',   name: 'Lloyds Banking (ADR)',     layer: 'Financials',        category: 'CEDEAR' },
  { ticker: 'MUFG',  name: 'Mitsubishi UFJ (ADR)',     layer: 'Financials',        category: 'CEDEAR' },
  { ticker: 'MFG',   name: 'Mizuho Financial (ADR)',   layer: 'Financials',        category: 'CEDEAR' },
  { ticker: 'NMR',   name: 'Nomura Holdings (ADR)',    layer: 'Financials',        category: 'CEDEAR' },
  { ticker: 'KB',    name: 'KB Financial (ADR)',       layer: 'Financials',        category: 'CEDEAR' },
  { ticker: 'HDB',   name: 'HDFC Bank (ADR)',          layer: 'Financials',        category: 'CEDEAR' },
  { ticker: 'IBN',   name: 'ICICI Bank (ADR)',         layer: 'Financials',        category: 'CEDEAR' },
  { ticker: 'BBD',   name: 'Banco Bradesco (ADR)',     layer: 'Financials',        category: 'CEDEAR' },
  { ticker: 'BSBR',  name: 'Santander Brasil (ADR)',   layer: 'Financials',        category: 'CEDEAR' },
  { ticker: 'ITUB',  name: 'Itaú Unibanco (ADR)',      layer: 'Financials',        category: 'CEDEAR' },
  { ticker: 'FNMA',  name: 'Fannie Mae',               layer: 'Financials',        category: 'CEDEAR' },
  { ticker: 'FMCC',  name: 'Freddie Mac',              layer: 'Financials',        category: 'CEDEAR' },

  // ── CEDEARs — Consumer Discretionary ─────────────────────────────────────────
  { ticker: 'WMT',   name: 'Walmart',                  layer: 'Consumer',          category: 'CEDEAR' },
  { ticker: 'HD',    name: 'Home Depot',               layer: 'Consumer',          category: 'CEDEAR' },
  { ticker: 'MCD',   name: "McDonald's",               layer: 'Consumer',          category: 'CEDEAR' },
  { ticker: 'SBUX',  name: 'Starbucks',                layer: 'Consumer',          category: 'CEDEAR' },
  { ticker: 'NKE',   name: 'Nike',                     layer: 'Consumer',          category: 'CEDEAR' },
  { ticker: 'DIS',   name: 'Disney',                   layer: 'Consumer',          category: 'CEDEAR' },
  { ticker: 'TGT',   name: 'Target',                   layer: 'Consumer',          category: 'CEDEAR' },
  { ticker: 'COST',  name: 'Costco',                   layer: 'Consumer',          category: 'CEDEAR' },
  { ticker: 'ROST',  name: 'Ross Stores',              layer: 'Consumer',          category: 'CEDEAR' },
  { ticker: 'ORLY',  name: "O'Reilly Auto",            layer: 'Consumer',          category: 'CEDEAR' },
  { ticker: 'TJX',   name: 'TJX Companies',           layer: 'Consumer',          category: 'CEDEAR' },
  { ticker: 'URBN',  name: 'Urban Outfitters',         layer: 'Consumer',          category: 'CEDEAR' },
  { ticker: 'ANF',   name: 'Abercrombie & Fitch',      layer: 'Consumer',          category: 'CEDEAR' },
  { ticker: 'HOG',   name: 'Harley-Davidson',          layer: 'Consumer',          category: 'CEDEAR' },
  { ticker: 'LVS',   name: 'Las Vegas Sands',          layer: 'Consumer',          category: 'CEDEAR' },
  { ticker: 'CCL',   name: 'Carnival Corp',            layer: 'Consumer',          category: 'CEDEAR' },
  { ticker: 'GM',    name: 'General Motors',           layer: 'Consumer',          category: 'CEDEAR' },
  { ticker: 'F',     name: 'Ford',                     layer: 'Consumer',          category: 'CEDEAR' },
  { ticker: 'STLA',  name: 'Stellantis',               layer: 'Consumer',          category: 'CEDEAR' },
  { ticker: 'HMC',   name: 'Honda Motor (ADR)',        layer: 'Consumer',          category: 'CEDEAR' },
  { ticker: 'TM',    name: 'Toyota (ADR)',             layer: 'Consumer',          category: 'CEDEAR' },
  { ticker: 'RACE',  name: 'Ferrari',                  layer: 'Consumer',          category: 'CEDEAR' },
  { ticker: 'TRIP',  name: 'TripAdvisor',              layer: 'Consumer',          category: 'CEDEAR' },
  { ticker: 'ARCO',  name: 'Arcos Dorados',            layer: 'Consumer',          category: 'CEDEAR' },
  { ticker: 'DEO',   name: 'Diageo (ADR)',             layer: 'Consumer',          category: 'CEDEAR' },

  // ── CEDEARs — Consumer Staples ────────────────────────────────────────────────
  { ticker: 'KO',    name: 'Coca-Cola',                layer: 'Staples',           category: 'CEDEAR' },
  { ticker: 'PEP',   name: 'PepsiCo',                  layer: 'Staples',           category: 'CEDEAR' },
  { ticker: 'PG',    name: 'Procter & Gamble',         layer: 'Staples',           category: 'CEDEAR' },
  { ticker: 'KMB',   name: 'Kimberly-Clark',           layer: 'Staples',           category: 'CEDEAR' },
  { ticker: 'CL',    name: 'Colgate-Palmolive',        layer: 'Staples',           category: 'CEDEAR' },
  { ticker: 'MDLZ',  name: 'Mondelez',                 layer: 'Staples',           category: 'CEDEAR' },
  { ticker: 'HSY',   name: 'Hershey',                  layer: 'Staples',           category: 'CEDEAR' },
  { ticker: 'SYY',   name: 'Sysco',                    layer: 'Staples',           category: 'CEDEAR' },
  { ticker: 'MO',    name: 'Altria',                   layer: 'Staples',           category: 'CEDEAR' },
  { ticker: 'PM',    name: 'Philip Morris Intl',       layer: 'Staples',           category: 'CEDEAR' },
  { ticker: 'UL',    name: 'Unilever (ADR)',           layer: 'Staples',           category: 'CEDEAR' },
  { ticker: 'DANOY', name: 'Danone (ADR)',             layer: 'Staples',           category: 'CEDEAR' },
  { ticker: 'WBA',   name: 'Walgreens',                layer: 'Staples',           category: 'CEDEAR' },
  { ticker: 'KOF',   name: 'Coca-Cola FEMSA (ADR)',    layer: 'Staples',           category: 'CEDEAR' },
  { ticker: 'FMX',   name: 'FEMSA (ADR)',              layer: 'Staples',           category: 'CEDEAR' },
  { ticker: 'ABEV',  name: 'Ambev (ADR)',              layer: 'Staples',           category: 'CEDEAR' },
  { ticker: 'BRFS',  name: 'BRF SA (ADR)',             layer: 'Staples',           category: 'CEDEAR' },

  // ── CEDEARs — Healthcare ──────────────────────────────────────────────────────
  { ticker: 'PFE',   name: 'Pfizer',                   layer: 'Healthcare',        category: 'CEDEAR' },
  { ticker: 'MRNA',  name: 'Moderna',                  layer: 'Healthcare',        category: 'CEDEAR' },
  { ticker: 'JNJ',   name: 'Johnson & Johnson',        layer: 'Healthcare',        category: 'CEDEAR' },
  { ticker: 'ABBV',  name: 'AbbVie',                   layer: 'Healthcare',        category: 'CEDEAR' },
  { ticker: 'LLY',   name: 'Eli Lilly',                layer: 'Healthcare',        category: 'CEDEAR' },
  { ticker: 'AMGN',  name: 'Amgen',                    layer: 'Healthcare',        category: 'CEDEAR' },
  { ticker: 'BMY',   name: 'Bristol-Myers Squibb',     layer: 'Healthcare',        category: 'CEDEAR' },
  { ticker: 'BIIB',  name: 'Biogen',                   layer: 'Healthcare',        category: 'CEDEAR' },
  { ticker: 'GILD',  name: 'Gilead Sciences',          layer: 'Healthcare',        category: 'CEDEAR' },
  { ticker: 'MDT',   name: 'Medtronic',                layer: 'Healthcare',        category: 'CEDEAR' },
  { ticker: 'DHR',   name: 'Danaher',                  layer: 'Healthcare',        category: 'CEDEAR' },
  { ticker: 'TMO',   name: 'Thermo Fisher',            layer: 'Healthcare',        category: 'CEDEAR' },
  { ticker: 'UNH',   name: 'UnitedHealth',             layer: 'Healthcare',        category: 'CEDEAR' },
  { ticker: 'CVS',   name: 'CVS Health',               layer: 'Healthcare',        category: 'CEDEAR' },
  { ticker: 'MRK',   name: 'Merck & Co',               layer: 'Healthcare',        category: 'CEDEAR' },
  { ticker: 'NVS',   name: 'Novartis (ADR)',           layer: 'Healthcare',        category: 'CEDEAR' },
  { ticker: 'AZN',   name: 'AstraZeneca (ADR)',        layer: 'Healthcare',        category: 'CEDEAR' },
  { ticker: 'GSK',   name: 'GSK (ADR)',                layer: 'Healthcare',        category: 'CEDEAR' },
  { ticker: 'BAYRY', name: 'Bayer (ADR)',              layer: 'Healthcare',        category: 'CEDEAR' },

  // ── CEDEARs — Energy ──────────────────────────────────────────────────────────
  { ticker: 'XOM',   name: 'ExxonMobil',               layer: 'Energy',            category: 'CEDEAR' },
  { ticker: 'CVX',   name: 'Chevron',                  layer: 'Energy',            category: 'CEDEAR' },
  { ticker: 'BP',    name: 'BP (ADR)',                 layer: 'Energy',            category: 'CEDEAR' },
  { ticker: 'SHEL',  name: 'Shell (ADR)',              layer: 'Energy',            category: 'CEDEAR' },
  { ticker: 'TTE',   name: 'TotalEnergies (ADR)',      layer: 'Energy',            category: 'CEDEAR' },
  { ticker: 'SLB',   name: 'Schlumberger',             layer: 'Energy',            category: 'CEDEAR' },
  { ticker: 'HAL',   name: 'Halliburton',              layer: 'Energy',            category: 'CEDEAR' },
  { ticker: 'BKR',   name: 'Baker Hughes',             layer: 'Energy',            category: 'CEDEAR' },
  { ticker: 'EQNR',  name: 'Equinor (ADR)',           layer: 'Energy',            category: 'CEDEAR' },
  { ticker: 'E',     name: 'Eni SpA (ADR)',            layer: 'Energy',            category: 'CEDEAR' },
  { ticker: 'PSX',   name: 'Phillips 66',              layer: 'Energy',            category: 'CEDEAR' },
  { ticker: 'VIST',  name: 'Vista Energy',             layer: 'Energy',            category: 'CEDEAR' },
  { ticker: 'GPRK',  name: 'GeoPark',                  layer: 'Energy',            category: 'CEDEAR' },
  { ticker: 'PBR',   name: 'Petrobras (ADR)',          layer: 'Energy',            category: 'CEDEAR' },
  { ticker: 'FSLR',  name: 'First Solar',              layer: 'Energy',            category: 'CEDEAR' },
  { ticker: 'EONGY', name: 'E.ON SE (ADR)',            layer: 'Energy',            category: 'CEDEAR' },

  // ── CEDEARs — Industrials / Aerospace ─────────────────────────────────────────
  { ticker: 'BA',    name: 'Boeing',                   layer: 'Industrials',       category: 'CEDEAR' },
  { ticker: 'CAT',   name: 'Caterpillar',              layer: 'Industrials',       category: 'CEDEAR' },
  { ticker: 'LMT',   name: 'Lockheed Martin',          layer: 'Industrials',       category: 'CEDEAR' },
  { ticker: 'GE',    name: 'GE Aerospace',             layer: 'Industrials',       category: 'CEDEAR' },
  { ticker: 'RTX',   name: 'RTX Corp',                 layer: 'Industrials',       category: 'CEDEAR' },
  { ticker: 'HON',   name: 'Honeywell',                layer: 'Industrials',       category: 'CEDEAR' },
  { ticker: 'DE',    name: 'Deere & Co',               layer: 'Industrials',       category: 'CEDEAR' },
  { ticker: 'FDX',   name: 'FedEx',                    layer: 'Industrials',       category: 'CEDEAR' },
  { ticker: 'UNP',   name: 'Union Pacific',            layer: 'Industrials',       category: 'CEDEAR' },
  { ticker: 'HWM',   name: 'Howmet Aerospace',         layer: 'Industrials',       category: 'CEDEAR' },
  { ticker: 'PCAR',  name: 'PACCAR',                   layer: 'Industrials',       category: 'CEDEAR' },
  { ticker: 'MMM',   name: '3M',                       layer: 'Industrials',       category: 'CEDEAR' },
  { ticker: 'IP',    name: 'International Paper',      layer: 'Industrials',       category: 'CEDEAR' },
  { ticker: 'JCI',   name: 'Johnson Controls',         layer: 'Industrials',       category: 'CEDEAR' },
  { ticker: 'IFF',   name: 'Intl Flavors & Fragrances',layer: 'Industrials',       category: 'CEDEAR' },
  { ticker: 'DOW',   name: 'Dow Inc',                  layer: 'Industrials',       category: 'CEDEAR' },
  { ticker: 'DD',    name: 'DuPont',                   layer: 'Industrials',       category: 'CEDEAR' },
  { ticker: 'DAL',   name: 'Delta Air Lines',          layer: 'Industrials',       category: 'CEDEAR' },
  { ticker: 'AAL',   name: 'American Airlines',        layer: 'Industrials',       category: 'CEDEAR' },
  { ticker: 'ERJ',   name: 'Embraer (ADR)',            layer: 'Industrials',       category: 'CEDEAR' },
  { ticker: 'CAAP',  name: 'Corp America Airports',    layer: 'Industrials',       category: 'CEDEAR' },
  { ticker: 'PAC',   name: 'Grupo Aeroportuario Pac.', layer: 'Industrials',       category: 'CEDEAR' },
  { ticker: 'ASR',   name: 'Grupo Aeroportuario Sur',  layer: 'Industrials',       category: 'CEDEAR' },
  { ticker: 'TV',    name: 'Grupo Televisa (ADR)',     layer: 'Industrials',       category: 'CEDEAR' },
  { ticker: 'AMX',   name: 'America Movil (ADR)',      layer: 'Industrials',       category: 'CEDEAR' },
  { ticker: 'DTEGY', name: 'Deutsche Telekom (ADR)',   layer: 'Industrials',       category: 'CEDEAR' },

  // ── CEDEARs — Mining / Materials ──────────────────────────────────────────────
  { ticker: 'NEM',   name: 'Newmont',                  layer: 'Mining',            category: 'CEDEAR' },
  { ticker: 'GOLD',  name: 'Barrick Gold',             layer: 'Mining',            category: 'CEDEAR' },
  { ticker: 'KGC',   name: 'Kinross Gold',             layer: 'Mining',            category: 'CEDEAR' },
  { ticker: 'AEM',   name: 'Agnico Eagle',             layer: 'Mining',            category: 'CEDEAR' },
  { ticker: 'PAAS',  name: 'Pan American Silver',      layer: 'Mining',            category: 'CEDEAR' },
  { ticker: 'FCX',   name: 'Freeport-McMoRan',         layer: 'Mining',            category: 'CEDEAR' },
  { ticker: 'BHP',   name: 'BHP Group (ADR)',          layer: 'Mining',            category: 'CEDEAR' },
  { ticker: 'RIO',   name: 'Rio Tinto (ADR)',          layer: 'Mining',            category: 'CEDEAR' },
  { ticker: 'VALE',  name: 'Vale (ADR)',               layer: 'Mining',            category: 'CEDEAR' },
  { ticker: 'GFI',   name: 'Gold Fields (ADR)',        layer: 'Mining',            category: 'CEDEAR' },
  { ticker: 'HMY',   name: 'Harmony Gold (ADR)',       layer: 'Mining',            category: 'CEDEAR' },
  { ticker: 'CDE',   name: 'Coeur Mining',             layer: 'Mining',            category: 'CEDEAR' },
  { ticker: 'HL',    name: 'Hecla Mining',             layer: 'Mining',            category: 'CEDEAR' },
  { ticker: 'MUX',   name: 'McEwen Mining',            layer: 'Mining',            category: 'CEDEAR' },
  { ticker: 'NUE',   name: 'Nucor',                    layer: 'Mining',            category: 'CEDEAR' },
  { ticker: 'X',     name: 'US Steel',                 layer: 'Mining',            category: 'CEDEAR' },
  { ticker: 'SCCO',  name: 'Southern Copper',          layer: 'Mining',            category: 'CEDEAR' },
  { ticker: 'GGB',   name: 'Gerdau (ADR)',             layer: 'Mining',            category: 'CEDEAR' },
  { ticker: 'SID',   name: 'CSN (ADR)',                layer: 'Mining',            category: 'CEDEAR' },
  { ticker: 'SUZ',   name: 'Suzano (ADR)',             layer: 'Mining',            category: 'CEDEAR' },
  { ticker: 'LAC',   name: 'Lithium Americas',         layer: 'Mining',            category: 'CEDEAR' },
  { ticker: 'LAR',   name: 'Lithium Argentina',        layer: 'Mining',            category: 'CEDEAR' },
  { ticker: 'NXE',   name: 'NexGen Energy',            layer: 'Mining',            category: 'CEDEAR' },
  { ticker: 'NG',    name: 'NovaGold Resources',       layer: 'Mining',            category: 'CEDEAR' },
  { ticker: 'CX',    name: 'Cemex (ADR)',              layer: 'Mining',            category: 'CEDEAR' },
  { ticker: 'BASFY', name: 'BASF SE (ADR)',            layer: 'Mining',            category: 'CEDEAR' },

  // ── CEDEARs — Telecom ─────────────────────────────────────────────────────────
  { ticker: 'T',     name: 'AT&T',                     layer: 'Telecom',           category: 'CEDEAR' },
  { ticker: 'VZ',    name: 'Verizon',                  layer: 'Telecom',           category: 'CEDEAR' },
  { ticker: 'TMUS',  name: 'T-Mobile US',              layer: 'Telecom',           category: 'CEDEAR' },
  { ticker: 'VOD',   name: 'Vodafone (ADR)',           layer: 'Telecom',           category: 'CEDEAR' },
  { ticker: 'ORAN',  name: 'Orange (ADR)',             layer: 'Telecom',           category: 'CEDEAR' },
  { ticker: 'TEF',   name: 'Telefónica (ADR)',         layer: 'Telecom',           category: 'CEDEAR' },
  { ticker: 'NGG',   name: 'National Grid (ADR)',      layer: 'Telecom',           category: 'CEDEAR' },
  { ticker: 'VIV',   name: 'Telefónica Brasil (ADR)',  layer: 'Telecom',           category: 'CEDEAR' },

  // ── CEDEARs — Ag / LatAm ──────────────────────────────────────────────────────
  { ticker: 'AGRO',  name: 'Adecoagro',                layer: 'Agriculture',       category: 'CEDEAR' },
  { ticker: 'BIOX',  name: 'Bioceres Crop Solutions',  layer: 'Agriculture',       category: 'CEDEAR' },
  { ticker: 'LND',   name: 'BrasilAgro (ADR)',         layer: 'Agriculture',       category: 'CEDEAR' },
  { ticker: 'BG',    name: 'Bunge Global',             layer: 'Agriculture',       category: 'CEDEAR' },
  { ticker: 'AKO-B', name: 'Embotelladora Andina',     layer: 'Agriculture',       category: 'CEDEAR' },

  // ── CEDEARs — Other / Crypto ──────────────────────────────────────────────────
  { ticker: 'RIOT',  name: 'Riot Platforms',           layer: 'Crypto',            category: 'CEDEAR' },
  { ticker: 'GT',    name: 'Goodyear',                 layer: 'Other',             category: 'CEDEAR' },
  { ticker: 'CAR',   name: 'Avis Budget',              layer: 'Other',             category: 'CEDEAR' },
  { ticker: 'XRX',   name: 'Xerox',                    layer: 'Other',             category: 'CEDEAR' },
  { ticker: 'AAP',   name: 'Advance Auto Parts',       layer: 'Other',             category: 'CEDEAR' },
  { ticker: 'AVY',   name: 'Avery Dennison',           layer: 'Other',             category: 'CEDEAR' },
  { ticker: 'AEG',   name: 'Aegon (ADR)',              layer: 'Other',             category: 'CEDEAR' },
  { ticker: 'BAK',   name: 'Braskem (ADR)',            layer: 'Other',             category: 'CEDEAR' },
  { ticker: 'EBR',   name: 'Eletrobras (ADR)',         layer: 'Other',             category: 'CEDEAR' },
  { ticker: 'CBD',   name: 'Pão de Açúcar (ADR)',      layer: 'Other',             category: 'CEDEAR' },
  { ticker: 'SBS',   name: 'Sabesp (ADR)',             layer: 'Other',             category: 'CEDEAR' },
  { ticker: 'ELP',   name: 'Copel (ADR)',              layer: 'Other',             category: 'CEDEAR' },
  { ticker: 'UGP',   name: 'Ultrapar (ADR)',           layer: 'Other',             category: 'CEDEAR' },

  // ── CEDEARs — ETFs ────────────────────────────────────────────────────────────
  { ticker: 'IBIT',  name: 'iShares Bitcoin Trust',    layer: 'ETF',               category: 'CEDEAR' },
  { ticker: 'XLK',   name: 'SPDR Technology ETF',      layer: 'ETF',               category: 'CEDEAR' },
  { ticker: 'XLV',   name: 'SPDR Healthcare ETF',      layer: 'ETF',               category: 'CEDEAR' },
  { ticker: 'XLC',   name: 'SPDR Comm. Services ETF',  layer: 'ETF',               category: 'CEDEAR' },
  { ticker: 'XLY',   name: 'SPDR Cons. Discret. ETF',  layer: 'ETF',               category: 'CEDEAR' },
  { ticker: 'XLP',   name: 'SPDR Cons. Staples ETF',   layer: 'ETF',               category: 'CEDEAR' },
  { ticker: 'XLI',   name: 'SPDR Industrials ETF',     layer: 'ETF',               category: 'CEDEAR' },
  { ticker: 'XLB',   name: 'SPDR Materials ETF',       layer: 'ETF',               category: 'CEDEAR' },
  { ticker: 'XLRE',  name: 'SPDR Real Estate ETF',     layer: 'ETF',               category: 'CEDEAR' },
  { ticker: 'IBB',   name: 'iShares Biotech ETF',      layer: 'ETF',               category: 'CEDEAR' },
  { ticker: 'IVW',   name: 'iShares S&P 500 Growth',   layer: 'ETF',               category: 'CEDEAR' },
  { ticker: 'IVE',   name: 'iShares S&P 500 Value',    layer: 'ETF',               category: 'CEDEAR' },
  { ticker: 'FXI',   name: 'iShares China Large-Cap',  layer: 'ETF',               category: 'CEDEAR' },
  { ticker: 'VEA',   name: 'Vanguard Dev. Markets ETF',layer: 'ETF',               category: 'CEDEAR' },

  // ── BYMA — Panel Líder (ADR tickers where available, .BA otherwise) ──────────
  { ticker: 'GGAL',  name: 'Grupo Galicia',            layer: 'Arg. Banks',        category: 'BYMA' },
  { ticker: 'BMA',   name: 'Banco Macro',              layer: 'Arg. Banks',        category: 'BYMA' },
  { ticker: 'SUPV',  name: 'Supervielle',              layer: 'Arg. Banks',        category: 'BYMA' },
  { ticker: 'BBAR',  name: 'BBVA Argentina',           layer: 'Arg. Banks',        category: 'BYMA' },
  { ticker: 'YPF',   name: 'YPF',                      layer: 'Arg. Energy',       category: 'BYMA' },
  { ticker: 'PAM',   name: 'Pampa Energía',            layer: 'Arg. Energy',       category: 'BYMA' },
  { ticker: 'CEPU',  name: 'Central Puerto',           layer: 'Arg. Energy',       category: 'BYMA' },
  { ticker: 'EDN',   name: 'Edenor',                   layer: 'Arg. Energy',       category: 'BYMA' },
  { ticker: 'TEO',   name: 'Telecom Argentina',        layer: 'Arg. Telecom',      category: 'BYMA' },
  { ticker: 'TX',    name: 'Ternium',                  layer: 'Arg. Industry',     category: 'BYMA' },
  { ticker: 'LOMA',  name: 'Loma Negra',               layer: 'Arg. Industry',     category: 'BYMA' },
  { ticker: 'CRESY', name: 'Cresud',                   layer: 'Arg. Agriculture',  category: 'BYMA' },
  { ticker: 'IRS',   name: 'IRSA',                     layer: 'Arg. Real Estate',  category: 'BYMA' },
  { ticker: 'TS',    name: 'Tenaris (ADR)',             layer: 'Arg. Industry',     category: 'BYMA' },
  // .BA tickers (no US ADR listing)
  { ticker: 'TGSU2.BA', name: 'Trans. Gas del Sur',   layer: 'Arg. Energy',       category: 'BYMA' },
  { ticker: 'TGNO4.BA', name: 'Trans. Gas del Norte', layer: 'Arg. Energy',       category: 'BYMA' },
  { ticker: 'CGPA2.BA', name: 'Capex SA',             layer: 'Arg. Energy',       category: 'BYMA' },
  { ticker: 'CECO2.BA', name: 'Central Costanera',    layer: 'Arg. Energy',       category: 'BYMA' },
  { ticker: 'ALUA.BA',  name: 'Aluar',                layer: 'Arg. Industry',     category: 'BYMA' },
  { ticker: 'TXAR.BA',  name: 'Ternium Argentina',    layer: 'Arg. Industry',     category: 'BYMA' },
  { ticker: 'MIRG.BA',  name: 'Mirgor',               layer: 'Arg. Industry',     category: 'BYMA' },
  { ticker: 'COME.BA',  name: 'Com. del Plata',       layer: 'Arg. Industry',     category: 'BYMA' },
  { ticker: 'TRAN.BA',  name: 'Transener',            layer: 'Arg. Industry',     category: 'BYMA' },
  { ticker: 'HARG.BA',  name: 'Holcim Argentina',     layer: 'Arg. Industry',     category: 'BYMA' },
  { ticker: 'CVH.BA',   name: 'Cablevisión Holding',  layer: 'Arg. Telecom',      category: 'BYMA' },
  { ticker: 'TECO2.BA', name: 'Telecom Arg. (local)', layer: 'Arg. Telecom',      category: 'BYMA' },
  { ticker: 'BYMA.BA',  name: 'BYMA',                 layer: 'Arg. Finance',      category: 'BYMA' },
  { ticker: 'VALO.BA',  name: 'Banco de Valores',     layer: 'Arg. Finance',      category: 'BYMA' },
  { ticker: 'BHIP.BA',  name: 'Banco Hipotecario',    layer: 'Arg. Finance',      category: 'BYMA' },
  { ticker: 'BPAT.BA',  name: 'Banco Patagonia',      layer: 'Arg. Finance',      category: 'BYMA' },
  { ticker: 'IRSA.BA',  name: 'IRSA (local)',         layer: 'Arg. Real Estate',  category: 'BYMA' },
  { ticker: 'CTIO.BA',  name: 'Consultatio RE',       layer: 'Arg. Real Estate',  category: 'BYMA' },
  { ticker: 'CRES.BA',  name: 'Cresud (local)',       layer: 'Arg. Agriculture',  category: 'BYMA' },
  { ticker: 'AGRO.BA',  name: 'Agrometal',            layer: 'Arg. Agriculture',  category: 'BYMA' },
  { ticker: 'GCLA.BA',  name: 'Grupo Clarín',         layer: 'Arg. Media',        category: 'BYMA' },
  { ticker: 'MOLI.BA',  name: 'Molinos Río de la Plata', layer: 'Arg. Consumer',  category: 'BYMA' },
  { ticker: 'RICH.BA',  name: 'Lab. Richmond',        layer: 'Arg. Healthcare',   category: 'BYMA' },
  { ticker: 'LOMA.BA',  name: 'Loma Negra (local)',   layer: 'Arg. Industry',     category: 'BYMA' },
]

// De-duplicate by ticker (keep first occurrence)
const _seen = new Set<string>()
export const STRATEGY_UNIVERSE: UniverseEntry[] = RAW_UNIVERSE.filter(e => {
  if (_seen.has(e.ticker)) return false
  _seen.add(e.ticker)
  return true
})

export interface StrategyRow {
  ticker: string
  name: string
  layer: string
  category: UniverseCategory
  price: number | null
  change1d: number | null

  momentum12_1: number | null
  momentumRank: number | null

  vol252: number | null
  volRank: number | null

  ma50: number | null
  ma200: number | null
  maSpread: number | null
  maSignal: 'golden' | 'death' | null

  return1m: number | null
  mrZscore: number | null

  pe: number | null
  pb: number | null
  ps: number | null
  evEbitda: number | null
  valueRank: number | null
}
