export interface InstrumentMeta {
  type: 'index' | 'etf' | 'fx' | 'commodity' | 'volatility' | 'crypto' | 'other'
  assetClass: string
  description: string
  region?: string
  category?: string
  relatedSymbols?: string[]
  expenseRatio?: number
}

export const INSTRUMENT_META: Record<string, InstrumentMeta> = {
  // ── U.S. Equity Indices ────────────────────────────────────────────────────
  '^GSPC': {
    type: 'index',
    assetClass: 'U.S. Equity Index',
    description: 'Market-cap weighted index of 500 leading publicly traded U.S. companies. The primary benchmark for U.S. large-cap equities and the most widely tracked stock market index worldwide.',
    region: 'United States',
    category: 'Large Cap Blend',
    relatedSymbols: ['^NDX', '^DJI', 'IWM', '^VIX', 'ACWI'],
  },
  '^IXIC': {
    type: 'index',
    assetClass: 'U.S. Equity Index',
    description: 'Broad composite index tracking all common stocks listed on the Nasdaq Stock Market, heavily weighted toward technology and growth companies.',
    region: 'United States',
    category: 'Technology / Growth',
    relatedSymbols: ['^NDX', '^GSPC', '^DJI', 'XLK', 'IWM'],
  },
  '^NDX': {
    type: 'index',
    assetClass: 'U.S. Equity Index',
    description: 'Modified market-cap weighted index of the 100 largest non-financial companies listed on the Nasdaq. Widely considered the benchmark for mega-cap technology and innovation.',
    region: 'United States',
    category: 'Large Cap Technology',
    relatedSymbols: ['^GSPC', '^IXIC', '^DJI', 'XLK', 'IWM'],
  },
  '^DJI': {
    type: 'index',
    assetClass: 'U.S. Equity Index',
    description: 'Price-weighted average of 30 blue-chip U.S. companies selected by S&P Dow Jones Indices. One of the oldest and most cited equity benchmarks, though its price-weighting is considered less representative than cap-weighted peers.',
    region: 'United States',
    category: 'Large Cap Blue Chip',
    relatedSymbols: ['^GSPC', '^NDX', '^IXIC', 'IWM', '^VIX'],
  },
  'IWM': {
    type: 'etf',
    assetClass: 'U.S. Equity ETF',
    description: 'iShares Russell 2000 ETF tracks the Russell 2000 Index, comprising approximately 2,000 small-cap U.S. companies. Serves as the primary benchmark for U.S. small-cap equities.',
    region: 'United States',
    category: 'Small Cap Blend',
    relatedSymbols: ['^GSPC', '^NDX', '^DJI', 'ACWI', 'EEM'],
    expenseRatio: 0.0019,
  },
  '^VIX': {
    type: 'volatility',
    assetClass: 'Volatility Index',
    description: "CBOE Volatility Index measures the market's expectation of 30-day S&P 500 volatility, derived from real-time options prices. Known as the 'fear gauge' — elevated readings signal market uncertainty or stress.",
    region: 'United States',
    category: 'Market Volatility',
    relatedSymbols: ['^GSPC', '^NDX', '^DJI', 'TLT', 'HYG'],
  },

  // ── U.S. Sector ETFs ──────────────────────────────────────────────────────
  'XLY': {
    type: 'etf',
    assetClass: 'Sector ETF',
    description: 'SPDR S&P Consumer Discretionary ETF tracks companies in the consumer discretionary sector including retail, autos, hotels, restaurants, and media.',
    region: 'United States',
    category: 'Consumer Discretionary',
    relatedSymbols: ['XLP', 'XLK', 'XLC', '^GSPC', 'XLF'],
    expenseRatio: 0.0009,
  },
  'XLP': {
    type: 'etf',
    assetClass: 'Sector ETF',
    description: 'SPDR S&P Consumer Staples ETF tracks companies providing essential consumer goods — food, beverages, household products, and personal care items.',
    region: 'United States',
    category: 'Consumer Staples',
    relatedSymbols: ['XLY', 'XLV', 'XLU', '^GSPC', 'XLF'],
    expenseRatio: 0.0009,
  },
  'XLE': {
    type: 'etf',
    assetClass: 'Sector ETF',
    description: 'SPDR S&P Energy ETF tracks oil, gas, and consumable fuels companies, including integrated majors, exploration & production, and energy equipment firms.',
    region: 'United States',
    category: 'Energy',
    relatedSymbols: ['GC=F', 'CL=F', 'BZ=F', '^GSPC', 'XLB'],
    expenseRatio: 0.0009,
  },
  'XLF': {
    type: 'etf',
    assetClass: 'Sector ETF',
    description: 'SPDR S&P Financial ETF tracks banks, insurance companies, diversified financials, and real estate companies, representing the financial sector of the S&P 500.',
    region: 'United States',
    category: 'Financials',
    relatedSymbols: ['XLRE', 'XLI', '^GSPC', 'TLT', 'HYG'],
    expenseRatio: 0.0009,
  },
  'XLV': {
    type: 'etf',
    assetClass: 'Sector ETF',
    description: 'SPDR S&P Health Care ETF tracks pharmaceuticals, biotechnology, managed health care, health care equipment and life sciences companies.',
    region: 'United States',
    category: 'Health Care',
    relatedSymbols: ['XLP', 'XLB', 'XLI', '^GSPC', 'XLK'],
    expenseRatio: 0.0009,
  },
  'XLI': {
    type: 'etf',
    assetClass: 'Sector ETF',
    description: 'SPDR S&P Industrials ETF covers aerospace & defense, industrial machinery, construction, transportation, and commercial services companies.',
    region: 'United States',
    category: 'Industrials',
    relatedSymbols: ['XLB', 'XLE', 'XLF', '^GSPC', 'XLC'],
    expenseRatio: 0.0009,
  },
  'XLB': {
    type: 'etf',
    assetClass: 'Sector ETF',
    description: 'SPDR S&P Materials ETF tracks chemicals, metals & mining, paper, packaging, and construction materials companies.',
    region: 'United States',
    category: 'Materials',
    relatedSymbols: ['XLE', 'XLI', 'GC=F', '^GSPC', 'XLU'],
    expenseRatio: 0.0009,
  },
  'XLRE': {
    type: 'etf',
    assetClass: 'Sector ETF',
    description: 'SPDR S&P Real Estate ETF tracks equity real estate investment trusts (REITs) and real estate management companies in the S&P 500.',
    region: 'United States',
    category: 'Real Estate',
    relatedSymbols: ['XLF', 'XLU', 'TLT', '^GSPC', 'MUB'],
    expenseRatio: 0.0009,
  },
  'XLK': {
    type: 'etf',
    assetClass: 'Sector ETF',
    description: 'SPDR S&P Technology ETF tracks the largest U.S. technology companies across software, semiconductors, hardware, and IT services.',
    region: 'United States',
    category: 'Technology',
    relatedSymbols: ['^NDX', '^IXIC', 'XLC', '^GSPC', 'XLY'],
    expenseRatio: 0.0009,
  },
  'XLC': {
    type: 'etf',
    assetClass: 'Sector ETF',
    description: 'SPDR S&P Communication Services ETF tracks media, entertainment, internet, telecom, and interactive media companies.',
    region: 'United States',
    category: 'Communication Services',
    relatedSymbols: ['XLK', 'XLY', '^NDX', '^GSPC', 'XLF'],
    expenseRatio: 0.0009,
  },
  'XLU': {
    type: 'etf',
    assetClass: 'Sector ETF',
    description: 'SPDR S&P Utilities ETF tracks electric, gas, and water utility companies — typically valued for their stable dividends and defensive characteristics.',
    region: 'United States',
    category: 'Utilities',
    relatedSymbols: ['XLRE', 'XLP', 'TLT', '^GSPC', 'XLF'],
    expenseRatio: 0.0009,
  },

  // ── Fixed Income ETFs ─────────────────────────────────────────────────────
  'TLT': {
    type: 'etf',
    assetClass: 'Fixed Income ETF',
    description: 'iShares 20+ Year Treasury Bond ETF tracks U.S. Treasury bonds with remaining maturities of 20 years or more. Highly sensitive to interest rate changes and widely used as a risk-off benchmark.',
    region: 'United States',
    category: 'Long-Duration Government',
    relatedSymbols: ['IEF', 'TIP', 'LQD', 'HYG', '^VIX'],
    expenseRatio: 0.0015,
  },
  'IEF': {
    type: 'etf',
    assetClass: 'Fixed Income ETF',
    description: 'iShares 7-10 Year Treasury Bond ETF provides exposure to U.S. Treasury bonds with maturities between 7 and 10 years — intermediate-duration government debt.',
    region: 'United States',
    category: 'Intermediate Government',
    relatedSymbols: ['TLT', 'TIP', 'LQD', 'HYG', 'MUB'],
    expenseRatio: 0.0015,
  },
  'MUB': {
    type: 'etf',
    assetClass: 'Fixed Income ETF',
    description: 'iShares National Muni Bond ETF tracks investment-grade municipal bonds issued by U.S. states and localities. Interest income is typically exempt from federal income tax.',
    region: 'United States',
    category: 'Municipal Bonds',
    relatedSymbols: ['TLT', 'IEF', 'LQD', 'XLRE', 'TIP'],
    expenseRatio: 0.0007,
  },
  'HYG': {
    type: 'etf',
    assetClass: 'Fixed Income ETF',
    description: 'iShares iBoxx High Yield Corporate Bond ETF tracks U.S.-dollar-denominated, below-investment-grade corporate bonds. A widely followed proxy for credit risk appetite.',
    region: 'United States',
    category: 'High Yield Corporate',
    relatedSymbols: ['LQD', 'TLT', 'IEF', '^VIX', 'XLF'],
    expenseRatio: 0.0049,
  },
  'LQD': {
    type: 'etf',
    assetClass: 'Fixed Income ETF',
    description: 'iShares iBoxx Investment Grade Corporate Bond ETF tracks investment-grade U.S. corporate bonds, offering a blend of credit spread exposure and interest rate duration.',
    region: 'United States',
    category: 'Investment Grade Corporate',
    relatedSymbols: ['HYG', 'TLT', 'IEF', 'MUB', 'TIP'],
    expenseRatio: 0.0014,
  },
  'TIP': {
    type: 'etf',
    assetClass: 'Fixed Income ETF',
    description: 'iShares TIPS Bond ETF tracks Treasury Inflation-Protected Securities, whose principal adjusts with CPI. Serves as a direct hedge against unexpected inflation.',
    region: 'United States',
    category: 'Inflation-Protected',
    relatedSymbols: ['TLT', 'IEF', 'LQD', 'GC=F', 'HYG'],
    expenseRatio: 0.0019,
  },

  // ── Currencies ────────────────────────────────────────────────────────────
  'DX-Y.NYB': {
    type: 'other',
    assetClass: 'Currency Index',
    description: 'U.S. Dollar Index measures the value of the USD against a basket of six major currencies (EUR, JPY, GBP, CAD, SEK, CHF), weighted by trade significance. A key macro barometer for USD strength.',
    region: 'Global',
    category: 'Dollar Index',
    relatedSymbols: ['EURUSD=X', 'USDJPY=X', 'GBPUSD=X', 'GC=F', 'TLT'],
  },
  'EURUSD=X': {
    type: 'fx',
    assetClass: 'Currency Pair',
    description: 'Euro / U.S. Dollar exchange rate — the most traded currency pair globally, representing relative monetary policy between the European Central Bank and the U.S. Federal Reserve.',
    region: 'Europe / United States',
    category: 'Major FX',
    relatedSymbols: ['USDJPY=X', 'GBPUSD=X', 'DX-Y.NYB', 'TLT', '^GDAXI'],
  },
  'USDJPY=X': {
    type: 'fx',
    assetClass: 'Currency Pair',
    description: 'U.S. Dollar / Japanese Yen exchange rate. A closely watched risk sentiment barometer — yen tends to strengthen during risk-off episodes due to its safe-haven status.',
    region: 'United States / Japan',
    category: 'Major FX',
    relatedSymbols: ['EURUSD=X', 'GBPUSD=X', 'DX-Y.NYB', '^N225', 'TLT'],
  },
  'GBPUSD=X': {
    type: 'fx',
    assetClass: 'Currency Pair',
    description: 'British Pound / U.S. Dollar exchange rate, commonly called "Cable." Sensitive to Bank of England policy, UK economic data, and political developments including Brexit aftereffects.',
    region: 'United Kingdom / United States',
    category: 'Major FX',
    relatedSymbols: ['EURUSD=X', 'USDJPY=X', 'DX-Y.NYB', '^FTSE', 'TLT'],
  },
  'BTC-USD': {
    type: 'crypto',
    assetClass: 'Cryptocurrency',
    description: 'Bitcoin (BTC) is the first and largest cryptocurrency by market capitalization, operating on a decentralized blockchain with a fixed supply of 21 million coins.',
    region: 'Global',
    category: 'Cryptocurrency',
    relatedSymbols: ['DX-Y.NYB', 'GC=F', '^VIX', '^GSPC', 'TLT'],
  },

  // ── Global Broad Market ETFs ───────────────────────────────────────────────
  'ACWI': {
    type: 'etf',
    assetClass: 'Global Equity ETF',
    description: 'iShares MSCI ACWI ETF tracks the MSCI All Country World Index, covering approximately 85% of the global investable equity market across 47 developed and emerging markets.',
    region: 'Global',
    category: 'Global Blend',
    relatedSymbols: ['^GSPC', 'EFA', 'EEM', 'VEA', 'IWM'],
    expenseRatio: 0.0032,
  },
  'EFA': {
    type: 'etf',
    assetClass: 'International Equity ETF',
    description: 'iShares MSCI EAFE ETF tracks large and mid-cap developed market equities outside the U.S. and Canada, covering Europe, Australasia, and the Far East.',
    region: 'Developed Markets ex-U.S.',
    category: 'International Large Cap',
    relatedSymbols: ['ACWI', 'VEA', 'EEM', '^GSPC', 'EURUSD=X'],
    expenseRatio: 0.0032,
  },
  'VEA': {
    type: 'etf',
    assetClass: 'International Equity ETF',
    description: 'Vanguard FTSE Developed Markets ETF provides broad exposure to large, mid, and small-cap developed market stocks outside North America.',
    region: 'Developed Markets ex-U.S.',
    category: 'International Blend',
    relatedSymbols: ['EFA', 'ACWI', 'EEM', '^GSPC', '^FTSE'],
    expenseRatio: 0.0005,
  },
  'EEM': {
    type: 'etf',
    assetClass: 'Emerging Market ETF',
    description: 'iShares MSCI Emerging Markets ETF tracks large and mid-cap equities in 24 emerging market countries including China, India, Brazil, and Taiwan.',
    region: 'Emerging Markets',
    category: 'Emerging Markets Blend',
    relatedSymbols: ['FXI', 'INDA', 'EWZ', 'ACWI', 'EFA'],
    expenseRatio: 0.0068,
  },

  // ── Global Developed Market Indices ───────────────────────────────────────
  '^GDAXI': {
    type: 'index',
    assetClass: 'Equity Index',
    description: "DAX Performance Index tracks the 40 largest and most liquid companies listed on the Frankfurt Stock Exchange, Germany's primary equity benchmark.",
    region: 'Germany / Europe',
    category: 'European Large Cap',
    relatedSymbols: ['^FTSE', '^FCHI', 'EURUSD=X', 'EFA', 'ACWI'],
  },
  '^FTSE': {
    type: 'index',
    assetClass: 'Equity Index',
    description: 'FTSE 100 Index tracks the 100 largest companies by market capitalisation listed on the London Stock Exchange. Heavily weighted toward energy, mining, and financial sectors.',
    region: 'United Kingdom',
    category: 'UK Large Cap',
    relatedSymbols: ['^GDAXI', '^FCHI', 'GBPUSD=X', 'EFA', 'ACWI'],
  },
  '^FCHI': {
    type: 'index',
    assetClass: 'Equity Index',
    description: "CAC 40 Index is a market-cap weighted measure of the 40 most significant stocks on the Euronext Paris exchange, France's primary equity benchmark.",
    region: 'France / Europe',
    category: 'European Large Cap',
    relatedSymbols: ['^GDAXI', '^FTSE', 'EURUSD=X', 'EFA', 'ACWI'],
  },
  '^AXJO': {
    type: 'index',
    assetClass: 'Equity Index',
    description: "S&P/ASX 200 Index tracks the 200 largest ASX-listed companies by float-adjusted market capitalisation. Australia's primary equity benchmark, with large exposure to financials and materials.",
    region: 'Australia',
    category: 'Australian Large Cap',
    relatedSymbols: ['EFA', 'VEA', 'ACWI', 'GC=F', 'CL=F'],
  },
  '^N225': {
    type: 'index',
    assetClass: 'Equity Index',
    description: 'Nikkei 225 is a price-weighted index of 225 large-cap companies on the Tokyo Stock Exchange, Japan\'s primary stock market benchmark.',
    region: 'Japan',
    category: 'Japanese Large Cap',
    relatedSymbols: ['USDJPY=X', 'EFA', 'VEA', 'ACWI', '^GSPC'],
  },

  // ── Global Emerging Market ETFs ───────────────────────────────────────────
  'EWZ': {
    type: 'etf',
    assetClass: 'Emerging Market ETF',
    description: "iShares MSCI Brazil ETF tracks large and mid-cap Brazilian equities. Brazil's market is heavily influenced by commodity exports, interest rate cycles, and political dynamics.",
    region: 'Brazil',
    category: 'Brazil Equity',
    relatedSymbols: ['EEM', 'FXI', 'INDA', 'EWW', 'GC=F'],
    expenseRatio: 0.0059,
  },
  'EWW': {
    type: 'etf',
    assetClass: 'Emerging Market ETF',
    description: 'iShares MSCI Mexico ETF tracks Mexican equities, capturing exposure to financials, consumer staples, and communications in one of Latin America\'s largest economies.',
    region: 'Mexico',
    category: 'Mexico Equity',
    relatedSymbols: ['EWZ', 'EEM', 'ACWI', 'EWY', 'EZA'],
    expenseRatio: 0.0050,
  },
  'EZA': {
    type: 'etf',
    assetClass: 'Emerging Market ETF',
    description: 'iShares MSCI South Africa ETF tracks South African equities including large-cap miners, banks, and consumer companies listed on the Johannesburg Stock Exchange.',
    region: 'South Africa',
    category: 'South Africa Equity',
    relatedSymbols: ['EEM', 'EWZ', 'FXI', 'GC=F', 'ACWI'],
    expenseRatio: 0.0059,
  },
  'FXI': {
    type: 'etf',
    assetClass: 'Emerging Market ETF',
    description: 'iShares China Large-Cap ETF tracks the FTSE China 50 Index, comprising the 50 largest Chinese stocks traded on the Hong Kong Stock Exchange.',
    region: 'China',
    category: 'China Large Cap',
    relatedSymbols: ['EEM', 'INDA', 'ACWI', 'EFA', 'EWZ'],
    expenseRatio: 0.0074,
  },
  'INDA': {
    type: 'etf',
    assetClass: 'Emerging Market ETF',
    description: 'iShares MSCI India ETF tracks large and mid-cap Indian equities, providing broad exposure to one of the fastest-growing major economies globally.',
    region: 'India',
    category: 'India Equity',
    relatedSymbols: ['EEM', 'FXI', 'ACWI', 'EWY', 'EFA'],
    expenseRatio: 0.0065,
  },
  'EWY': {
    type: 'etf',
    assetClass: 'Emerging Market ETF',
    description: "iShares MSCI South Korea ETF tracks Korean equities, with significant exposure to technology and semiconductors through companies like Samsung and SK Hynix.",
    region: 'South Korea',
    category: 'South Korea Equity',
    relatedSymbols: ['EEM', 'FXI', 'INDA', 'ACWI', 'XLK'],
    expenseRatio: 0.0058,
  },

  // ── Commodities ───────────────────────────────────────────────────────────
  'GC=F': {
    type: 'commodity',
    assetClass: 'Commodity Futures',
    description: 'COMEX Gold Futures track the spot price of gold. Gold serves as a traditional safe-haven asset, inflation hedge, and alternative to fiat currency in investor portfolios.',
    region: 'Global',
    category: 'Precious Metals',
    relatedSymbols: ['SI=F', 'CL=F', 'TIP', 'DX-Y.NYB', '^VIX'],
  },
  'CL=F': {
    type: 'commodity',
    assetClass: 'Commodity Futures',
    description: 'WTI Crude Oil Futures traded on NYMEX represent light, sweet crude oil — the U.S. benchmark for oil pricing. Highly sensitive to global supply-demand dynamics and OPEC+ decisions.',
    region: 'Global',
    category: 'Energy',
    relatedSymbols: ['BZ=F', 'NG=F', 'XLE', 'DX-Y.NYB', 'GC=F'],
  },
  'NG=F': {
    type: 'commodity',
    assetClass: 'Commodity Futures',
    description: 'NYMEX Natural Gas Futures track Henry Hub natural gas prices. A key energy commodity influenced by weather patterns, storage levels, LNG exports, and seasonal demand.',
    region: 'United States',
    category: 'Energy',
    relatedSymbols: ['CL=F', 'BZ=F', 'XLE', 'XLU', 'GC=F'],
  },
  'BZ=F': {
    type: 'commodity',
    assetClass: 'Commodity Futures',
    description: 'Brent Crude Oil Futures are the global benchmark for oil pricing, representing North Sea crude. Brent is referenced in roughly two-thirds of world crude oil contracts.',
    region: 'Global',
    category: 'Energy',
    relatedSymbols: ['CL=F', 'NG=F', 'XLE', 'DX-Y.NYB', 'EWZ'],
  },
  'SI=F': {
    type: 'commodity',
    assetClass: 'Commodity Futures',
    description: 'COMEX Silver Futures track silver spot prices. Silver has dual demand as both a precious metal store of value and an industrial metal used in electronics and solar panels.',
    region: 'Global',
    category: 'Precious Metals',
    relatedSymbols: ['GC=F', 'CL=F', 'TIP', 'XLB', 'DX-Y.NYB'],
  },
}

export function getInstrumentMeta(symbol: string): InstrumentMeta {
  return (
    INSTRUMENT_META[symbol] ?? {
      type: 'other',
      assetClass: 'Financial Instrument',
      description: 'No description available for this instrument.',
    }
  )
}
