import Link from 'next/link'

export const metadata = { title: 'Terms of Service — Insic' }

const EFFECTIVE_DATE = 'June 9, 2026'

export default function TermsPage() {
  return (
    <div className="min-h-dvh bg-[#F0F1F6]">
      <div className="mx-auto max-w-2xl px-4 sm:px-6 py-12 sm:py-24">

        <div className="mb-8">
          <Link href="/" className="inline-flex items-center min-h-[44px] text-sm text-[#2563EB] hover:underline">← Back to Insic</Link>
        </div>

        <h1 className="text-2xl sm:text-3xl font-bold text-[#06101F] mb-2">Terms of Service</h1>
        <p className="text-sm text-[#8A95A6] mb-8 sm:mb-10">Effective date: {EFFECTIVE_DATE}</p>

        <div className="prose prose-slate max-w-none space-y-8 text-sm text-[#566174] leading-relaxed">

          {/* ── 1 ── */}
          <section>
            <h2 className="text-base sm:text-lg font-semibold text-[#06101F] mb-2 mt-6">1. Acceptance of Terms</h2>
            <p>
              By accessing or using Insic (&quot;the Service&quot;, &quot;we&quot;, &quot;us&quot;, &quot;our&quot;), you
              (&quot;User&quot;, &quot;you&quot;) agree to be bound by these Terms of Service (&quot;Terms&quot;) and our{' '}
              <Link href="/privacy" className="text-[#2563EB] hover:underline">Privacy Policy</Link>, which is
              incorporated by reference. If you do not agree to all of these Terms, you must not access or
              use the Service.
            </p>
            <p className="mt-2">
              We reserve the right to modify these Terms at any time. If we make material changes, we will
              notify registered users by email at least 14 days before the changes take effect. Your continued
              use of the Service after that date constitutes acceptance of the updated Terms. If you do not
              agree to the updated Terms, you must stop using the Service before they take effect.
            </p>
          </section>

          {/* ── 2 ── */}
          <section>
            <h2 className="text-base sm:text-lg font-semibold text-[#06101F] mb-2 mt-6">2. Not Financial Advice</h2>
            <p className="font-semibold text-[#06101F]">
              NOTHING ON THIS PLATFORM CONSTITUTES FINANCIAL, INVESTMENT, LEGAL, OR TAX ADVICE OF ANY KIND.
            </p>
            <p className="mt-2">
              All content — including DCF models, fair value estimates, health scores, valuation multiples,
              conviction scores, scenario analyses, reverse DCF outputs, ETF analysis, trading signals,
              portfolio tracking data, and any other outputs generated by the Service — is provided for{' '}
              <strong>informational and educational purposes only</strong>. These are model outputs based on
              publicly available data and mathematical assumptions. They are <strong>not</strong> recommendations
              to buy, sell, hold, or otherwise transact in any security, financial instrument, or asset of
              any kind.
            </p>
            <p className="mt-2">
              Financial models are inherently limited and speculative. Inputs may be inaccurate, incomplete,
              or outdated. Assumptions embedded in models may not reflect reality. Market conditions change.
              Even well-constructed, professionally maintained models frequently produce incorrect estimates.
              Past performance of any security, strategy, or model does not guarantee or indicate future results.
            </p>
            <p className="mt-2">
              <strong>You are solely and entirely responsible for your own investment decisions and their
              outcomes.</strong> Always consult a qualified, licensed, and regulated financial advisor before
              making any investment decision. The Service is a research tool — it is not a substitute for
              professional financial advice.
            </p>
            <p className="mt-2">
              To the maximum extent permitted by applicable law, you expressly waive any claim against Insic
              arising from investment losses or financial harm of any kind resulting from use of, reliance on,
              or interpretation of any content, model output, or information provided by the Service.
            </p>
          </section>

          {/* ── 3 ── */}
          <section>
            <h2 className="text-base sm:text-lg font-semibold text-[#06101F] mb-2 mt-6">3. Eligibility</h2>
            <p>
              You must be at least 18 years old to use the Service. By using it, you represent and warrant
              that you are at least 18, that you have the legal capacity to enter into a binding contract,
              and that your use of the Service does not violate any applicable law or regulation in your
              jurisdiction.
            </p>
            <p className="mt-2">
              The Service is not available to persons who have previously been suspended or removed from the
              Service by us.
            </p>
          </section>

          {/* ── 4 ── */}
          <section>
            <h2 className="text-base sm:text-lg font-semibold text-[#06101F] mb-2 mt-6">4. Account Registration and Security</h2>
            <p>
              Accounts are created via Google OAuth. You are responsible for all activity that occurs under
              your account. You agree to notify us immediately at{' '}
              <a href="mailto:hello@insic.app" className="text-[#2563EB] hover:underline">hello@insic.app</a>{' '}
              if you suspect unauthorized use of your account.
            </p>
            <p className="mt-2">
              We reserve the right to suspend or permanently terminate accounts, without prior notice or
              liability, for any reason, including but not limited to violation of these Terms, abuse of the
              Service, fraudulent conduct, or inactivity.
            </p>
            <p className="mt-2">
              You may delete your account at any time by contacting us. Upon deletion, your personal data
              will be removed in accordance with our Privacy Policy.
            </p>
          </section>

          {/* ── 5 ── */}
          <section>
            <h2 className="text-base sm:text-lg font-semibold text-[#06101F] mb-2 mt-6">5. Subscriptions, Billing, and Refunds</h2>

            <p className="font-medium text-[#566174] mt-2">Free Plan</p>
            <p>
              The free plan provides limited access to the Service at no charge. Free plan features and usage
              limits may be changed at any time at our discretion.
            </p>

            <p className="font-medium text-[#566174] mt-4">Pro Plan — Paid Subscription</p>
            <p>
              The Pro plan is a recurring subscription billed on a monthly or annual basis, as selected at
              the time of purchase. Subscriptions are processed through our third-party payment processor.
              By subscribing, you authorize recurring charges to your payment method at the applicable
              billing interval.
            </p>
            <p className="mt-2">
              Prices are displayed at checkout and may be subject to applicable taxes. We reserve the right
              to change subscription pricing with at least 30 days&apos; notice to current subscribers.
            </p>

            <p className="font-medium text-[#566174] mt-4">Free Trial</p>
            <p>
              Where a free trial is offered, it begins on the date you provide your payment details. At the
              end of the trial period, you will be automatically charged for the Pro plan unless you cancel
              before the trial ends.
            </p>

            <p className="font-medium text-[#566174] mt-4">Cancellation</p>
            <p>
              You may cancel your subscription at any time through your account&apos;s billing portal. Cancellation
              takes effect at the end of the current billing period. You will retain access to Pro features
              until the end of the paid period. We do not provide refunds or credits for partial periods,
              unused features, or accidental renewals unless required by applicable law.
            </p>

            <p id="refunds" className="font-medium text-[#566174] mt-4">Refunds</p>
            <p>
              All sales are final. Except where required by applicable consumer protection law, we do not
              offer refunds. If you believe you were charged in error, contact us at{' '}
              <a href="mailto:hello@insic.app" className="text-[#2563EB] hover:underline">hello@insic.app</a>{' '}
              within 14 days of the charge and we will review the matter in good faith.
            </p>

            <p className="font-medium text-[#566174] mt-4">Failed Payments</p>
            <p>
              If a payment fails, your account will be downgraded to the free plan. We may retry failed
              payments and will notify you by email.
            </p>
          </section>

          {/* ── 6 ── */}
          <section>
            <h2 className="text-base sm:text-lg font-semibold text-[#06101F] mb-2 mt-6">6. Acceptable Use</h2>
            <p>You agree not to use the Service to:</p>
            <ul className="list-disc pl-5 mt-2 space-y-1">
              <li>Violate any applicable law, regulation, or third-party right</li>
              <li>Scrape, crawl, index, or systematically extract data from the platform by any means</li>
              <li>Access the Service through bots, scripts, or automated tools except as expressly permitted</li>
              <li>Reverse engineer, decompile, disassemble, or attempt to extract the source code</li>
              <li>Resell, sublicense, redistribute, or commercially exploit any output or feature of the Service without our express written permission</li>
              <li>Interfere with or disrupt the integrity or performance of the Service or its infrastructure</li>
              <li>Attempt to gain unauthorized access to any account, system, or network associated with the Service</li>
              <li>Impersonate any person or entity, or misrepresent your affiliation with any person or entity</li>
              <li>Share your account credentials with others or allow multiple users to access the Service through a single account</li>
              <li>Use the Service to develop or train a competing product or service</li>
            </ul>
            <p className="mt-2">
              We reserve the right to investigate suspected violations and, at our discretion, take any
              action we deem appropriate, including suspending or terminating access without notice.
            </p>
          </section>

          {/* ── 7 ── */}
          <section>
            <h2 className="text-base sm:text-lg font-semibold text-[#06101F] mb-2 mt-6">7. Data Sources and Accuracy</h2>
            <p>
              Financial data is sourced from third parties including Yahoo Finance, Financial Modeling Prep,
              FRED (Federal Reserve Economic Data), and Damodaran&apos;s publicly available research. We do not
              control these sources and cannot guarantee the accuracy, completeness, or timeliness of any
              data. Errors or delays in source data will produce errors or delays in model outputs.
            </p>
            <p className="mt-2">
              We do not warrant that the Service will be available without interruption or that outputs will
              be error-free. Market data may be delayed. We expressly disclaim all warranties, express or
              implied, relating to the accuracy or completeness of any data or output.
            </p>
          </section>

          {/* ── 8 ── */}
          <section>
            <h2 className="text-base sm:text-lg font-semibold text-[#06101F] mb-2 mt-6">8. Intellectual Property</h2>
            <p>
              All content, design, code, algorithms, branding, trademarks, and materials on the Service
              are the exclusive property of Insic or its licensors and are protected by applicable intellectual
              property laws. You may not copy, reproduce, modify, distribute, or create derivative works of
              any part of the Service without our prior written permission, except for personal,
              non-commercial use strictly in connection with using the Service as intended.
            </p>
            <p className="mt-2">
              You retain ownership of any content you input into the Service (e.g., custom valuation
              assumptions). By inputting such content, you grant us a non-exclusive, royalty-free licence
              to store and process it solely for the purpose of providing the Service to you.
            </p>
          </section>

          {/* ── 9 ── */}
          <section>
            <h2 className="text-base sm:text-lg font-semibold text-[#06101F] mb-2 mt-6">9. Disclaimer of Warranties</h2>
            <p>
              THE SERVICE IS PROVIDED &quot;AS IS&quot; AND &quot;AS AVAILABLE&quot; WITHOUT WARRANTIES OF ANY KIND, EITHER
              EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS
              FOR A PARTICULAR PURPOSE, TITLE, AND NON-INFRINGEMENT.
            </p>
            <p className="mt-2">
              We do not warrant that: (a) the Service will be uninterrupted, timely, secure, or error-free;
              (b) any errors will be corrected; (c) the results obtained from using the Service will be
              accurate, reliable, or suitable for any purpose; or (d) any output constitutes investment advice.
            </p>
          </section>

          {/* ── 10 ── */}
          <section>
            <h2 className="text-base sm:text-lg font-semibold text-[#06101F] mb-2 mt-6">10. Limitation of Liability</h2>
            <p>
              TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, INSIC AND ITS OWNERS, OPERATORS, EMPLOYEES,
              AGENTS, LICENSORS, AND SERVICE PROVIDERS SHALL NOT BE LIABLE FOR ANY:
            </p>
            <ul className="list-disc pl-5 mt-2 space-y-1">
              <li>INVESTMENT LOSSES OR FINANCIAL HARM OF ANY KIND ARISING FROM RELIANCE ON ANY SERVICE OUTPUT</li>
              <li>INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, PUNITIVE, OR EXEMPLARY DAMAGES</li>
              <li>LOSS OF PROFITS, REVENUE, DATA, GOODWILL, OR BUSINESS OPPORTUNITY</li>
              <li>DAMAGES ARISING FROM SERVICE UNAVAILABILITY, ERRORS, OR DATA INACCURACIES</li>
              <li>ANY OTHER DAMAGES ARISING OUT OF OR IN CONNECTION WITH YOUR USE OF THE SERVICE</li>
            </ul>
            <p className="mt-2">
              IN NO EVENT SHALL OUR AGGREGATE LIABILITY TO YOU FOR ALL CLAIMS ARISING FROM YOUR USE OF THE
              SERVICE EXCEED THE GREATER OF: (A) THE TOTAL AMOUNT YOU PAID TO US IN THE 12 MONTHS PRECEDING
              THE CLAIM, OR (B) €100 EUR.
            </p>
            <p className="mt-2">
              Some jurisdictions do not allow the exclusion or limitation of certain damages, so some of
              the above limitations may not apply to you. In such cases, our liability is limited to the
              maximum extent permitted by law.
            </p>
          </section>

          {/* ── 11 ── */}
          <section>
            <h2 className="text-base sm:text-lg font-semibold text-[#06101F] mb-2 mt-6">11. Indemnification</h2>
            <p>
              You agree to defend, indemnify, and hold harmless Insic and its owners, operators, employees,
              agents, and service providers from and against any claims, damages, losses, liabilities, costs,
              and expenses (including reasonable legal fees) arising from: (a) your use of the Service;
              (b) your violation of these Terms; (c) your violation of any third-party right; or (d) any
              investment decision you make based on Service outputs.
            </p>
          </section>

          {/* ── 12 ── */}
          <section>
            <h2 className="text-base sm:text-lg font-semibold text-[#06101F] mb-2 mt-6">12. Dispute Resolution</h2>
            <p>
              In the event of any dispute, claim, or controversy arising out of or relating to these Terms
              or the Service, the parties agree to first attempt to resolve the matter through good-faith
              negotiation. Either party may initiate this process by sending written notice to the other
              describing the dispute. The parties will have 30 days from receipt of such notice to attempt
              informal resolution before either party may pursue formal remedies.
            </p>
            <p className="mt-2">
              If informal resolution fails, disputes shall be submitted to binding arbitration under the
              rules of a recognized arbitration body, on an individual basis. <strong>You waive any right
              to participate in a class action lawsuit or class-wide arbitration against Insic.</strong>
            </p>
            <p className="mt-2">
              Nothing in this section prevents either party from seeking emergency injunctive or other
              equitable relief from a court of competent jurisdiction to prevent irreparable harm.
            </p>
          </section>

          {/* ── 13 ── */}
          <section>
            <h2 className="text-base sm:text-lg font-semibold text-[#06101F] mb-2 mt-6">13. Governing Law and Jurisdiction</h2>
            <p>
              These Terms and any dispute arising from them are governed by and construed in accordance with
              applicable law, without regard to conflict of law principles. For users located in the European
              Union, mandatory consumer protection provisions of your country of residence also apply and are
              not affected by this clause.
            </p>
          </section>

          {/* ── 14 ── */}
          <section>
            <h2 className="text-base sm:text-lg font-semibold text-[#06101F] mb-2 mt-6">14. Termination</h2>
            <p>
              We may suspend or terminate your access to the Service immediately, without prior notice or
              liability, for any reason, including if you breach these Terms. Upon termination, your right to
              use the Service ceases immediately. Sections 2, 8, 9, 10, 11, 12, and 13 survive termination.
            </p>
            <p className="mt-2">
              You may terminate your account at any time. Termination does not entitle you to a refund of
              any subscription fees already paid, except as required by applicable law.
            </p>
          </section>

          {/* ── 15 ── */}
          <section>
            <h2 className="text-base sm:text-lg font-semibold text-[#06101F] mb-2 mt-6">15. Service Changes and Availability</h2>
            <p>
              We reserve the right to modify, suspend, or discontinue any part of the Service at any time,
              with or without notice. We are not liable to you or any third party for any modification,
              suspension, or discontinuation of the Service. We do not guarantee any specific level of
              uptime or availability.
            </p>
          </section>

          {/* ── 16 ── */}
          <section>
            <h2 className="text-base sm:text-lg font-semibold text-[#06101F] mb-2 mt-6">16. Severability and Waiver</h2>
            <p>
              If any provision of these Terms is found to be invalid, illegal, or unenforceable, that
              provision will be modified to the minimum extent necessary to make it enforceable, or severed
              if modification is not possible, and the remaining provisions will continue in full force.
            </p>
            <p className="mt-2">
              Our failure to enforce any right or provision of these Terms does not constitute a waiver of
              that right or provision. A waiver is only effective if made in writing and signed by an
              authorized representative of Insic.
            </p>
          </section>

          {/* ── 17 ── */}
          <section>
            <h2 className="text-base sm:text-lg font-semibold text-[#06101F] mb-2 mt-6">17. Entire Agreement</h2>
            <p>
              These Terms, together with the Privacy Policy and any other policies or agreements linked
              herein, constitute the entire agreement between you and Insic regarding the Service and
              supersede all prior or contemporaneous agreements, representations, or understandings.
            </p>
          </section>

          {/* ── 18 ── */}
          <section>
            <h2 className="text-base sm:text-lg font-semibold text-[#06101F] mb-2 mt-6">18. Contact</h2>
            <p>
              Questions about these Terms? Reach us at{' '}
              <a href="mailto:hello@insic.app" className="text-[#2563EB] hover:underline">
                hello@insic.app
              </a>.
            </p>
          </section>

        </div>

        <div className="mt-12 pt-8 border-t border-[#E3E1DA] flex flex-wrap gap-4 text-sm text-[#8A95A6]">
          <Link href="/privacy" className="hover:text-[#566174] transition-colors">Privacy Policy</Link>
          <Link href="/" className="hover:text-[#566174] transition-colors">Back to home</Link>
        </div>

      </div>
    </div>
  )
}
